import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ThemeChanger from "@/components/theme-changer";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header>
            <div className="flex justify-between">
              <div>HEADER</div>
              <ThemeChanger />
            </div>
          </header>
          <main className="flex-1">{children}</main>
          <footer>FOOTER</footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
